spring.application.name=colorscustom

# URL de ton site (local)
app.baseUrl=http://localhost:8080

# Stripe (dev)
stripe.secretKey=sk_test_...
stripe.publicKey=pk_test_...

# Webhook Stripe (IMPORTANT: même nom que dans ton code)
